### ISSUE TITLE
AttributeError when adding sleep time

### ISSUE THREAD

**Issue by s1hofmann** [andreas-hofmann/besdd#1]
*Error:* AttributeError at /1/sleep/quickadd/

*Steps to reproduce:*

- Follow setup guide
- Click *+sleep* in navbar

*Stacktrace:*

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/1/sleep/quickadd/

Django Version: 3.0.5
Python Version: 3.7.3
Installed Applications:
['slogger.apps.SloggerConfig',
 'registration.apps.RegistrationConfig',
 'bootstrap4',
 'bootstrap_datepicker_plus',
 'crispy_forms',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/Users/s1hofmann/Documents/git/besdd/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/s1hofmann/Documents/git/besdd/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/s1hofmann/Documents/git/besdd/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/s1hofmann/Documents/git/besdd/venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/s1hofmann/Documents/git/besdd/slogger/decorators.py", line 21, in wrapper
    return view(request, *args, **kwargs)
  File "/Users/s1hofmann/Documents/git/besdd/slogger/views.py", line 47, in quick_add_sleepphase
    if sp.dt and sp.dt_end:

Exception Type: AttributeError at /1/sleep/quickadd/
Exception Value: 'NoneType' object has no attribute 'dt'
```

**Comment by andreas-hofmann** [comment]
Fixed with 26dd30ab29b61f. Thanks!
